const Router = require('express')
const router = new Router()
const userRouter = require('./userRouter')
const productRouter = require('./productRouter')
const categoryRouter = require('./categoryRouter')
const sellerRouter = require('./sellerRouter')
const orderRouter = require('./orderRouter')
const basketRouter = require('./basketRouter')
const favoriteRouter = require('./favoriteRouter')
const recentlyViewedRouter = require('./recentlyViewedRouter')
const searchRouter = require('./searchRouter')
const adminRouter = require('./adminRouter')

router.use('/user', userRouter)
router.use('/product', productRouter)
router.use('/category', categoryRouter)
router.use('/seller', sellerRouter)
router.use('/order', orderRouter)
router.use('/basket', basketRouter)
router.use('/favorites', favoriteRouter)
router.use('/recentlyViewed', recentlyViewedRouter)
router.use('/search', searchRouter)
router.use('/admin', adminRouter)

module.exports = router