FROM node:20-slim

# Install build essentials for native modules like bcrypt
# RUN apt-get update && apt-get install -y \
#     python3 \
#     make \
#     g++ \
#     && rm -rf /var/lib/apt/lists/*

# WORKDIR /app


COPY package.json package.json

RUN npm install -omit=dev

COPY . .

CMD ["node", "index.js"]